# executando normal em 14-07-2024 -- 21:03

FROM node:20.10.0-alpine3.19
RUN apk update && apk add curl

RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.53.0

USER node
WORKDIR /app

# requsito do projeto - server.js
EXPOSE 8080

# processo rodando apenas para desenvolver

CMD ["tail", "-f" , "/dev/null"]